/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FavoriteColor {
  'id' : string,
  'color' : HexColor,
  'timestamp' : Time,
  'harmonyPalette' : string,
}
export interface HarmonyPalette {
  'triadic' : Array<HexColor>,
  'styleTip' : string,
  'analogous' : Array<HexColor>,
  'complementary' : Array<HexColor>,
}
export interface HexColor { 'hex' : string, 'name' : string }
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'emailVerified' : boolean,
  'displayName' : string,
  'email' : string,
  'gender' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavoriteColor' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countUserFavorites' : ActorMethod<[], bigint>,
  'deleteFavoriteById' : ActorMethod<[string], boolean>,
  'deleteUserAccount' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<FavoriteColor>>,
  'getHarmonyAdvice' : ActorMethod<[string], HarmonyPalette>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyEmail' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];