/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'emailVerified' : IDL.Bool,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
});
export const HexColor = IDL.Record({ 'hex' : IDL.Text, 'name' : IDL.Text });
export const Time = IDL.Int;
export const FavoriteColor = IDL.Record({
  'id' : IDL.Text,
  'color' : HexColor,
  'timestamp' : Time,
  'harmonyPalette' : IDL.Text,
});
export const HarmonyPalette = IDL.Record({
  'triadic' : IDL.Vec(HexColor),
  'styleTip' : IDL.Text,
  'analogous' : IDL.Vec(HexColor),
  'complementary' : IDL.Vec(HexColor),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavoriteColor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countUserFavorites' : IDL.Func([], [IDL.Nat], ['query']),
  'deleteFavoriteById' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteUserAccount' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(FavoriteColor)], ['query']),
  'getHarmonyAdvice' : IDL.Func([IDL.Text], [HarmonyPalette], []),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyEmail' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'emailVerified' : IDL.Bool,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
  });
  const HexColor = IDL.Record({ 'hex' : IDL.Text, 'name' : IDL.Text });
  const Time = IDL.Int;
  const FavoriteColor = IDL.Record({
    'id' : IDL.Text,
    'color' : HexColor,
    'timestamp' : Time,
    'harmonyPalette' : IDL.Text,
  });
  const HarmonyPalette = IDL.Record({
    'triadic' : IDL.Vec(HexColor),
    'styleTip' : IDL.Text,
    'analogous' : IDL.Vec(HexColor),
    'complementary' : IDL.Vec(HexColor),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavoriteColor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countUserFavorites' : IDL.Func([], [IDL.Nat], ['query']),
    'deleteFavoriteById' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteUserAccount' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(FavoriteColor)], ['query']),
    'getHarmonyAdvice' : IDL.Func([IDL.Text], [HarmonyPalette], []),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyEmail' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };